### ISSUE TITLE
mac-arm批量下载合集时占用cpu高

### ISSUE THREAD

**Issue by atomxing** [systemmin/wxdown#13]
macbook air m3，15.2系统。
批量下载合集时占用cpu高。具体原因打开【活动监视器】可以看到启用了几百个wkhtmltopdf进程，导致cpu很大一部分损失在进程切换。

建议：可以新增配置wkhtmltopdf进程数。看cpu核心数，一般8个以内即可。
![image](https://github.com/user-attachments/assets/d65ecc4f-3a86-4e1e-b342-9011215f2602)

**Comment by systemmin** [comment]
```yaml
# 采集线程配置
thread:
  # 同时下载 HTML 线程数量
  html: 10
  # 同时下载图片线程数量
  image: 20
```

改这个配置，html 5 image 10。可自行调整试试，找到最佳值
